### ISSUE TITLE
Error saving the member profile form in FE

### ISSUE THREAD

**Issue by zodit** [heimrichhannot/contao-email2username#1]
I used the original Contao module to let members edit their profile data. The user can edit the form, but saving there is a Fatal error. I included all available fields but i still have the error. 
My Contao log below.

`[02-Feb-2018 10:33:14 Europe/Berlin] PHP Fatal error: Uncaught exception 'TypeError' with message 'Argument 1 passed to tl_member_email2username::setUsernameFromEmail() must be an instance of DataContainer, instance of Contao\FrontendUser given, called in /usr/www/users/cortec/system/modules/core/modules/ModulePersonalData.php on line 356' thrown in /usr/www/users/cortec/system/modules/email2username/dca/tl_member.php on line 18
#0 /usr/www/users/cortec/system/modules/core/modules/ModulePersonalData.php(356): tl_member_email2username->setUsernameFromEmail(Object(Contao\FrontendUser), Object(Contao\ModulePersonalData))
#1 /usr/www/users/cortec/system/modules/core/modules/Module.php(287): Contao\ModulePersonalData->compile()
#2 /usr/www/users/cortec/system/modules/core/modules/ModulePersonalData.php(60): Contao\Module->generate()
#3 /usr/www/users/cortec/system/modules/core/elements/ContentModule.php(59): Contao\ModulePersonalData->generate()
#4 /usr/www/users/cortec/system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
#5 /usr/www/users/cortec/system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#6 /usr/www/users/cortec/system/modules/tags/modules/ModuleArticle.php(26): Contao\ModuleArticle->compile()
#7 /usr/www/users/cortec/system/modules/core/modules/Module.php(287): Aurealis\ModuleArticle->compile()
#8 /usr/www/users/cortec/system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#9 /usr/www/users/cortec/system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#10 /usr/www/users/cortec/system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#11 /usr/www/users/cortec/system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#12 /usr/www/users/cortec/system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#13 /usr/www/users/cortec/index.php(20): Contao\FrontendIndex->run()
#14 {main}`

**Comment by Defcon0** [comment]
OK, just fixed that one. Please use upcoming tag 1.1.4.

**Comment by zodit** [comment]
Bug fixed, thank you
